language: ruby
services:
  - docker

cache:
  directories:
    - $HOME/docker

matrix:
  include:
   - arch: amd64
     env: PLATFORM="x86_64"
   - arch: arm64
     env: PLATFORM="arm64v8"
   - arch: ppc64le
     env: PLATFORM="ppc64le"
   - arch: s390x
     env: PLATFORM="s390x"

script:
  - PLATFORM=$PLATFORM TRAVIS_COMMIT=$TRAVIS_COMMIT ./build.sh

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: focal
